static const char *petscmachineinfo = "\n"
"-----------------------------------------\n"
"Libraries compiled on 2020-07-16 00:43:16 on white11 \n"
"Machine characteristics: Linux-3.10.0-862.el7.ppc64le-ppc64le-with-redhat-7.5-Maipo\n"
"Using PETSc directory: /ascldap/users/snikolo/move/DEMSI_newLAMMPS/petsc-install\n"
"Using PETSc arch: \n"
"-----------------------------------------\n";
static const char *petsccompilerinfo = "\n"
"Using C compiler: mpicc  -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -fstack-protector -fvisibility=hidden -g3  \n"
"Using Fortran compiler: mpif90  -Wall -ffree-line-length-0 -Wno-unused-dummy-argument -g    \n"
"-----------------------------------------\n";
static const char *petsccompilerflagsinfo = "\n"
"Using include paths: -I/ascldap/users/snikolo/move/DEMSI_newLAMMPS/petsc-install/include\n"
"-----------------------------------------\n";
static const char *petsclinkerinfo = "\n"
"Using C linker: mpicc\n"
"Using Fortran linker: mpif90\n"
"Using libraries: -Wl,-rpath,/ascldap/users/snikolo/move/DEMSI_newLAMMPS/petsc-install/lib -L/ascldap/users/snikolo/move/DEMSI_newLAMMPS/petsc-install/lib -lpetsc -Wl,-rpath,/ascldap/users/snikolo/move/DEMSI_newLAMMPS/petsc-install/lib -L/ascldap/users/snikolo/move/DEMSI_newLAMMPS/petsc-install/lib -Wl,-rpath,/home/projects/ppc64le-pwr8-nvidia/openmpi/3.1.0/gcc/7.2.0/cuda/9.2.88/lib -L/home/projects/ppc64le-pwr8-nvidia/openmpi/3.1.0/gcc/7.2.0/cuda/9.2.88/lib -Wl,-rpath,/home/projects/ppc64le-pwr8-nvidia/cuda/9.2.88/extras/CUPTI/lib64 -L/home/projects/ppc64le-pwr8-nvidia/cuda/9.2.88/extras/CUPTI/lib64 -Wl,-rpath,/home/projects/ppc64le/gcc/7.2.0/lib64 -L/home/projects/ppc64le/gcc/7.2.0/lib64 -Wl,-rpath,/home/projects/ppc64le-pwr8/openblas/0.3.1/gcc/7.2.0/lib -L/home/projects/ppc64le-pwr8/openblas/0.3.1/gcc/7.2.0/lib -Wl,-rpath,/home/projects/ppc64le/git/2.10.1/lib -L/home/projects/ppc64le/git/2.10.1/lib -Wl,-rpath,/home/projects/ppc64le/python/2.7.12/lib -L/home/projects/ppc64le/python/2.7.12/lib -Wl,-rpath,/home/projects/ppc64le-pwr8-nvidia/netcdf/4.6.1/openmpi/3.1.0/gcc/7.2.0/cuda/9.2.88/lib -L/home/projects/ppc64le-pwr8-nvidia/netcdf/4.6.1/openmpi/3.1.0/gcc/7.2.0/cuda/9.2.88/lib -Wl,-rpath,/home/projects/ppc64le-pwr8-nvidia/hdf5/1.8.20/openmpi/3.1.0/gcc/7.2.0/cuda/9.2.88/lib -L/home/projects/ppc64le-pwr8-nvidia/hdf5/1.8.20/openmpi/3.1.0/gcc/7.2.0/cuda/9.2.88/lib -Wl,-rpath,/home/projects/ppc64le/zlib/1.2.8/lib -L/home/projects/ppc64le/zlib/1.2.8/lib -Wl,-rpath,/home/projects/ppc64le-pwr8-nvidia/pnetcdf-exo/1.9.0/openmpi/3.1.0/gcc/7.2.0/cuda/9.2.88/lib -L/home/projects/ppc64le-pwr8-nvidia/pnetcdf-exo/1.9.0/openmpi/3.1.0/gcc/7.2.0/cuda/9.2.88/lib -Wl,-rpath,/home/projects/ppc64le-pwr8/boost/1.65.1/gcc/7.2.0/lib -L/home/projects/ppc64le-pwr8/boost/1.65.1/gcc/7.2.0/lib -Wl,-rpath,/home/projects/ppc64le/java/ibm/sdk/8.0.0/lib -L/home/projects/ppc64le/java/ibm/sdk/8.0.0/lib -Wl,-rpath,/home/projects/ppc64le/papi/5.5.1/lib -L/home/projects/ppc64le/papi/5.5.1/lib -Wl,-rpath,/home/projects/ppc64le-pwr8-nvidia/cuda/9.2.88/lib64 -L/home/projects/ppc64le-pwr8-nvidia/cuda/9.2.88/lib64 -Wl,-rpath,/home/projects/ppc64le/gcc/7.2.0/lib -L/home/projects/ppc64le/gcc/7.2.0/lib -Wl,-rpath,/home/projects/ppc64le/gcc/7.2.0/lib/gcc/powerpc64le-unknown-linux-gnu/7.2.0 -L/home/projects/ppc64le/gcc/7.2.0/lib/gcc/powerpc64le-unknown-linux-gnu/7.2.0 -Wl,-rpath,/home/projects/ppc64le/binutils/2.30.0/lib -L/home/projects/ppc64le/binutils/2.30.0/lib -Wl,-rpath,/usr/lib/gcc/ppc64le-redhat-linux/4.8.5 -L/usr/lib/gcc/ppc64le-redhat-linux/4.8.5 -Wl,-rpath,/home/projects/ppc64le/binutils/2.30.0/powerpc64le-unknown-linux-gnu/lib -L/home/projects/ppc64le/binutils/2.30.0/powerpc64le-unknown-linux-gnu/lib -lflapack -lfblas -lX11 -lm -lstdc++ -ldl -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lgfortran -lm -lgfortran -lm -lgcc_s -lpthread -lstdc++ -ldl\n"
"-----------------------------------------\n";
