#!/bin/bash -ex
cmake $HOME/src/netcdf-4.5.0 \
-DCMAKE_BUILD_TYPE:STRING=Release \
-DCMAKE_INSTALL_PREFIX:PATH=$HOME/install/gcc/netcdf-demsi \
-DBUILD_SHARED_LIBS:BOOL=ON \
-DCMAKE_C_COMPILER:FILEPATH=$HOME/install/gcc/mpich/bin/mpicc \
-DCMAKE_CXX_COMPILER:FILEPATH=$HOME/install/gcc/mpich/bin/mpicxx \
-DENABLE_EXAMPLES:BOOL=OFF \
-DENABLE_DISKLESS:BOOL=OFF \
-DENABLE_DAP:BOOL=OFF \
-DENABLE_DAP_REMOTE_TESTS:BOOL=OFF \
-DENABLE_TESTS:BOOL=OFF \
-DENABLE_NETCDF_4:BOOL=OFF \
2>&1 | tee config_log
